version: '2'
services:
  postgres:
    image: postgres:latest
    environment:
     - POSTGRES_PASSWORD=mysecretpassword
    ports:
     - "5432:5432"
  node-people-api:
    build: .
    ports:
     - "3001:3001"
    environment:
     - POSTGRES_PASSWORD=mysecretpassword
     - POSTGRES_HOST=postgres
    links:
     - postgres
    depends_on:
     - postgres